import { useState } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="card">
      <p>Advice #117</p>
      <h3>"This will be the advice that will be generated by this API"</h3>
    </div>
  );
}

export default App;
