import "./App.css";
import divider from "./assets/images/pattern-divider-desktop.svg";
import dice from "./assets/images/icon-dice.svg";

function App() {
  return (
    <div className="card">
      <p>Advice #117</p>
      <h3>
        &ldquo; This will be the advice that will be generated by this API.
        &rdquo;
      </h3>
      <img
        src={divider}
        alt="divider"
        width="100%"
        style={{ marginBottom: "1.5rem" }}
      />
      <div className="dice">
        <img src={dice} alt="dice roller" width={20} />
      </div>
    </div>
  );
}

export default App;
